export const CATEGORY_EMOJI_MAP: Record<number, string> = {
  1: '🍔',
  2: '☕',
  3: '🧼',
  4: '👚',
  5: '🚌',
  6: '🏥',
  7: '✏️',
  8: '🎉',
  9: '💸',
  10: '🏠',
  11: '📄',
  12: '💰',
  13: '🎨',
  14: '💅',
  15: '🎭',
};

export const EMOTION_SVG_MAP: Record<number, string> = {
  1: '/svg/emo/happy.svg',
  2: '/svg/emo/flut.svg',
  3: '/svg/emo/proud.svg',
  4: '/svg/emo/thanks.svg',
  5: '/svg/emo/annoy.svg',
  6: '/svg/emo/angry.svg',
  7: '/svg/emo/anxios.svg',
  8: '/svg/emo/sad.svg',
  9: '/svg/emo/stress.svg',
  10: '/svg/emo/depressed.svg',
  11: '/svg/emo/boring.svg',
  12: '/svg/emo/tired.svg',
  13: '/svg/emo/emptiness.svg',
  14: '/svg/emo/lonely.svg',
  15: '/svg/emo/impulse.svg',
};
